[font]
size = 11

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[general]
import = ["/home/amueller/workspace/amue/dotfiles/.config/alacitty/dracula.toml"]
