import = ["/home/amue/git/alacritty-master/dracula.toml"]
# import = ["/home/amue/git/tokyonight.nvim/extras/alacritty/tokyonight_night.toml"]
[font]
size = 11

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"
