[[language]]
name = "rust"

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language-server.rust-analyzer.config]
checkOnSave = {command = "clippy"}
cargo = {allFeatures = true}
procMacro = {enable = true }
auto-format = true
