[[language]]
name = "c"
rulers = [80]

[[language]]
name = "rust"
rulers = [100]

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language-server.rust-analyzer.config]
check.command = "clippy"
cargo = {allFeatures = true}
procMacro = {enable = true }
auto-format = tru

[[language]]
name = "xml"
rulers = [100]
file-types = [ "xml", "svg", "xsd", "xslt", "xsl" ]
#auto-format = true
formatter = { command = "xmllint", args = ["--format", "-"] }
language-servers = [ "xml" ]

[language-server.xml]
command = "lemminx-linux"
